version: "3.8"

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - sqlite_data:/app/db
    environment:
      - NODE_ENV=production
      - DB_PATH=/app/db
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:3000/api-docs",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - API_HOST=api
      - API_PORT=3000
    depends_on:
      - api
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:80",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  sqlite_data:
    name: sample-rest-api-db
